#!/bin/bash

#
# Copyright (c) 2015, Erigones, s. r. o. All rights reserved.
#

set -o errexit
set -o pipefail

PATH=/usr/bin:/usr/sbin
. /lib/svc/share/fs_include.sh
. /lib/sdc/config.sh


USBMOUNTPOINT="/mnt/$(svcprop -p "joyentfs/usb_mountpoint" svc:/system/filesystem/smartdc)"
SYS_ZPOOL=$(svcprop -p config/zpool smartdc/init)
declare BOOTED_FROM_HDD

load_sdc_config

function abort
{
    printf "\nFactory reset aborted.\n"

    if /bin/bootparams | grep "^headnode=true" > /dev/null 2>&1; then
        unmount_usb
    fi

    exit 1
}

function mount_usb
{
    if mount | grep "^${USB_MNT}" >/dev/null 2>&1; then
        return 0
    fi

    USBKEYS=$(/usr/bin/disklist -a)
    for key in ${USBKEYS}; do
        if [[ `/usr/sbin/fstyp /dev/dsk/${key}p0:1` == 'pcfs' ]]; then
            /usr/sbin/mount -F pcfs -o foldcase,noatime /dev/dsk/${key}p0:1 \
                ${USBMOUNTPOINT};
            if [[ $? == "0" ]]; then
                if [[ ! -f ${USBMOUNTPOINT}/.joyliveusb ]]; then
                    /usr/sbin/umount ${USBMOUNTPOINT};
                else
                    break;
                fi
            fi
        fi
    done

    if mount | grep "^${USB_MNT}" >/dev/null 2>&1; then
        echo "Error: Could not mount ${USB_MNT}" 1>&2
        return 0
    fi
}

function unmount_usb
{
    if mount | grep "^${USB_MNT}" >/dev/null 2>&1; then
        return 0
    fi

    /usr/sbin/umount ${USBMOUNTPOINT}
}

trap abort SIGINT

BOOTED_FROM_HDD=1
mounted "/" "-" "zfs" < /etc/mnttab || BOOTED_FROM_HDD=0

if [ ${BOOTED_FROM_HDD} -eq 1 ]; then
    printf "This script works only when system is running from USB drive."
    exit 0
fi

printf "WARNING: This machine will delete ALL ZFS pools after reboot and re-run the installer!.\n"
read -p "Do you want to proceed with the factory reset? (y/n) " -n1

if [[ ${REPLY} =~ ^[Yy]$ ]]; then
    printf "\n\nThis will destroy ALL DATA on ${SYS_ZPOOL} pool, including potential customer data.\n"
    read -p "Are you sure? (y/n) " -n1

    if [[ ${REPLY} =~ ^[Yy]$ ]]; then

        if /bin/bootparams | grep "^headnode=true" > /dev/null 2>&1; then
            rm -f ${USBMOUNTPOINT}/config
        fi

        zfs set smartdc:factoryreset=yes ${SYS_ZPOOL}/var

        printf "\n\nRebooting in 5 seconds ... "
        sleep 5
        printf "now!\n"

        reboot
    else
        abort
    fi
else
    abort
fi

exit 0
